In [1]:
%tensorflow_version 1.x
import tensorflow as tf
import numpy as np
print(tf.__version__)

TensorFlow 1.x selected.
1.15.2


In [2]:
# DICTIONARY method for NLP inputs 
sent = 'Shaktiman is red in color. Pikachu is yellow in color. He is not a rich duck.'
corpus_lower = sent.lower()
words = []
for word in corpus_lower.split():
  if word != '.':
    word = word.replace('.','')
    words.append(word)

words


['shaktiman',
 'is',
 'red',
 'in',
 'color',
 'pikachu',
 'is',
 'yellow',
 'in',
 'color',
 'he',
 'is',
 'not',
 'a',
 'rich',
 'duck']

In [3]:
unique_words = set(words)
unique_words

{'a',
 'color',
 'duck',
 'he',
 'in',
 'is',
 'not',
 'pikachu',
 'red',
 'rich',
 'shaktiman',
 'yellow'}

In [7]:
word2int = {}
int2word = {}
vocab_size = len(unique_words)
for i,word in enumerate(unique_words):
  word2int[word] = i
  int2word[i] = word 
print(word2int)
print(int2word)

{'rich': 0, 'a': 1, 'color': 2, 'red': 3, 'pikachu': 4, 'is': 5, 'in': 6, 'not': 7, 'he': 8, 'duck': 9, 'shaktiman': 10, 'yellow': 11}
{0: 'rich', 1: 'a', 2: 'color', 3: 'red', 4: 'pikachu', 5: 'is', 6: 'in', 7: 'not', 8: 'he', 9: 'duck', 10: 'shaktiman', 11: 'yellow'}


In [8]:
raw_sentences = sent.split('.')
sentences = []
for sentence in raw_sentences:
  sentences.append(sentence.split())

print(sentences)



[['Shaktiman', 'is', 'red', 'in', 'color'], ['Pikachu', 'is', 'yellow', 'in', 'color'], ['He', 'is', 'not', 'a', 'rich', 'duck'], []]


In [9]:
sentences = sentences[:-1]
sentences

[['Shaktiman', 'is', 'red', 'in', 'color'],
 ['Pikachu', 'is', 'yellow', 'in', 'color'],
 ['He', 'is', 'not', 'a', 'rich', 'duck']]

In [11]:
# Autocomplete 
# [INPUT]-> 1 output word 

# ML Algo-> y = mx + c
# y => next word
# y = weights * inputs + bias 
# weights = 1-D filters
# inputs-> words provided

# next_word = weights * previous_word + bias 
# ALL POSSIBLE COMBINATIONS of WORD PAIRS 

# filter_pairs -> [prev, next]
window_size = 2
data = []
for sentence in sentences:
  for wordId,word in enumerate(sentence):
    for nxword in sentence[max(wordId - window_size,0):min(wordId + window_size, len(sentence))+1]:
      if nxword != word:
        data.append([word,nxword])

data
#LIMIT for all possible combination 
# from min to max possible lengths 
# 

[['Shaktiman', 'is'],
 ['Shaktiman', 'red'],
 ['is', 'Shaktiman'],
 ['is', 'red'],
 ['is', 'in'],
 ['red', 'Shaktiman'],
 ['red', 'is'],
 ['red', 'in'],
 ['red', 'color'],
 ['in', 'is'],
 ['in', 'red'],
 ['in', 'color'],
 ['color', 'red'],
 ['color', 'in'],
 ['Pikachu', 'is'],
 ['Pikachu', 'yellow'],
 ['is', 'Pikachu'],
 ['is', 'yellow'],
 ['is', 'in'],
 ['yellow', 'Pikachu'],
 ['yellow', 'is'],
 ['yellow', 'in'],
 ['yellow', 'color'],
 ['in', 'is'],
 ['in', 'yellow'],
 ['in', 'color'],
 ['color', 'yellow'],
 ['color', 'in'],
 ['He', 'is'],
 ['He', 'not'],
 ['is', 'He'],
 ['is', 'not'],
 ['is', 'a'],
 ['not', 'He'],
 ['not', 'is'],
 ['not', 'a'],
 ['not', 'rich'],
 ['a', 'is'],
 ['a', 'not'],
 ['a', 'rich'],
 ['a', 'duck'],
 ['rich', 'not'],
 ['rich', 'a'],
 ['rich', 'duck'],
 ['duck', 'a'],
 ['duck', 'rich']]

In [13]:
window_size = 1
data_single = []
for sentence in sentences:
  for wordId,word in enumerate(sentence):
    for nxword in sentence[max(wordId - window_size,0):min(wordId + window_size, len(sentence))+1]:
      if nxword != word:
        data_single.append([word,nxword])

data_single

[['Shaktiman', 'is'],
 ['is', 'Shaktiman'],
 ['is', 'red'],
 ['red', 'is'],
 ['red', 'in'],
 ['in', 'red'],
 ['in', 'color'],
 ['color', 'in'],
 ['Pikachu', 'is'],
 ['is', 'Pikachu'],
 ['is', 'yellow'],
 ['yellow', 'is'],
 ['yellow', 'in'],
 ['in', 'yellow'],
 ['in', 'color'],
 ['color', 'in'],
 ['He', 'is'],
 ['is', 'He'],
 ['is', 'not'],
 ['not', 'is'],
 ['not', 'a'],
 ['a', 'not'],
 ['a', 'rich'],
 ['rich', 'a'],
 ['rich', 'duck'],
 ['duck', 'rich']]

In [16]:
# ENCODING techniques
# SENTIMENT analysis-> label encoding 
# [hello, worlds,..]-> [0,1...]

# One-Hot Encoding
# Sales City Profit     ->.   Sales.  CITY_BLR.   CITY_MAA. CITY_NDLS Profit
#. 1.    BLR.  100                       1         0         0
#. 2.    MAA.  200                       0         1          0
#. 3.    MAA.  100                       0         1         0
#. 4.    NDLS.   10.                     0          0        1
#. 5.    BLR.   50
#. 6.    MAA.   20

# Profit = w1*sales + w2*city_blr + w3*city_maa + bias 
# for MAA specific, BLR = 0, for BLR specific, MAA=0
# for MAA, blr*w2 =0 , for BLR, maa*w3 = 0


In [17]:
# ONE HOT ENCODING for my dictionary
# EVERY WORD in my dictionary should be 1 hot encoded!!!

def Encoder(datapointindex, vocab_size):
  temp = np.zeros(vocab_size)
  temp[datapointindex] = 1
  return temp



In [21]:
trainx = []
trainy = []
for worddata in data:
  try:
    trainx.append(Encoder(word2int[worddata[0]], vocab_size))
    trainy.append(Encoder(word2int[worddata[1]], vocab_size))
  except:
    continue



In [22]:
trainy

[array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0.