In [1]:
# POOLING LAYERS
%tensorflow_version 1.x
import tensorflow as tf
import numpy as np
print(tf.__version__)

TensorFlow 1.x selected.
1.15.2


In [4]:
temp = [ 0., 0., 1., 0., 0.,2., 1., 1., 0., 0.]
values = tf.reshape(temp, [1,1,2,5])
# final 5 elements -> 2 lists-> 1 list -> 1 list

In [6]:
values
# LAZY evaluation
# TF-> complete picture only, then execution within a TF session

<tf.Tensor 'Reshape:0' shape=(1, 1, 2, 5) dtype=float32>

Lazy v/s Eager Evaluation

ops. --------  Lazy.-----  Eager. 

a=1 ----------- OK -------- 1

b=2 ----------- OK ------- 2

c= a + b ------ OK ------- 3

print(c) ------ EXECUTE()->"3" -------- "3"


In [8]:
session = tf.Session()
print('original')
print(temp)
print('*******')
print('reshaped')
print(session.run(values))
session.close()


original
[0.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1.0, 1.0, 0.0, 0.0]
*******
reshaped
[[[[0. 0. 1. 0. 0.]
   [2. 1. 1. 0. 0.]]]]


In [11]:
avgpool = tf.nn.pool(input=values, window_shape=(1,2), 
                     pooling_type='AVG', padding='VALID')
maxpool = tf.nn.pool(input=values, window_shape=(1,2), 
                     pooling_type='MAX', padding='VALID')

In [12]:
session = tf.Session()
print('original')
print(temp)
print('*******')
print('reshaped')
print(session.run(values))
print('*******')
print('avg_pool')
print(session.run(avgpool))
print('*******')
print('max_pool;')
print(session.run(maxpool))
session.close()

original
[0.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1.0, 1.0, 0.0, 0.0]
*******
reshaped
[[[[0. 0. 1. 0. 0.]
   [2. 1. 1. 0. 0.]]]]
*******
avg_pool
[[[[1.  0.5 1.  0.  0. ]]]]
*******
max_pool;
[[[[2. 1. 1. 0. 0.]]]]


In [ ]:
# CV/NLP-> MAX_pool -> data compression 
#          AVG_POOL-> blur an image! 

